services:
  app:
    image: pullwise/prinfoservice-prod:latest
    container_name: prinfoservice
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/etc/nginx/
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      nginx:
        condition: service_healthy
    volumes:
      - letsencrypt:/etc/letsencrypt
      - certbot_challenges:/var/www/certbot
    entrypoint: >
      /bin/sh -c "
      until curl -f http://nginx/.well-known/acme-challenge/; do
        echo 'Waiting for Nginx...';
        sleep 5;
      done;
      echo 'Nginx is up, requesting certificate...';
      certbot certonly --webroot -w /var/www/certbot \
        -d posttopurchase.store -d www.posttopurchase.store \
        --email pullwise@outlook.com --agree-tos --non-interactive --rsa-key-size 4096;
      "

volumes:
  letsencrypt:
  certbot_challenges: