services:
  app:
    image: pullwise/prinfoservice-prod:latest
    container_name: prinfoservice
    restart: always
    ports:
      - "8080:8080"
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    restart: always
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: >
      sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
      --email pullwise@outlook.com --agree-tos --no-eff-email --force-renewal
      -d posttopurchase.store -d www.posttopurchase.store &&
      cp /etc/letsencrypt/live/posttopurchase.store/fullchain.pem /etc/letsencrypt/live/posttopurchase.store/privkey.pem /var/www/certbot/"